#!/bin/sh

alias \
	home="cd $HOME" \
  bib="vim $HOME/.config/bib" \
	ali="vim $HOME/.config/shell/aliasrc" \
	mpv="mpv --window-scale=0.25" \
	yt="yt-dlp -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4'" \
	yta="yt -ci -f 'bestaudio[ext=m4a]'" \
	keymap="vim $HOME/.config/qmk_firmware/keyboards/boardsource/5x12/keymaps/leegerken/keymap.c" \
	webpush="rsync -avz ~/iCloud/Website/ root@leegerken.org:/var/www/leegerken/ --delete" \
	webpull="rsync -avz root@leegerken.org:/var/www/leegerken/ ~/iCloud/leegerken/ --delete" \
	cal="calcurse" \
	cfg="git --git-dir=$HOME/.config/.git/ --work-tree=$HOME" \
	web="git --git-dir=$HOME/iCloud/leegerken/.git/ --work-tree=$HOME/iCloud/leegerken" \

alias \
	evim='vim $HOME/.config/vim/vimrc' \
	elf='vim $HOME/.config/lf/lfrc' \
	ebash='vim $HOME/.bashrc' \
	est='vim $HOME/.local/src/st/config.h' \
	edwm='vim $HOME/.local/src/dwm/config.h' \
	etmux='vim $HOME/.config/tmux/tmux.conf' \
	eyab='vim $HOME/.config/yabai/yabairc' \
	esk='vim $HOME/.config/skhd/skhdrc' \

alias \
	ta='tmux attach -t' \
	tn='tmux new -s' \
