#!/bin/sh

# general
alias \
  reload="source $HOME/.bashrc" \
  ls="ls -a"  \
  home="cd $HOME" \
	ali="vim $HOME/.config/shell/aliasrc" \
	lf='ranger --choosedir=/tmp/.rangerdir; LASTDIR=`cat /tmp/.rangerdir`; cd "$LASTDIR"' \
	mpv="mpv --window-scale=0.25" \
#yt="yt-dlp -f 'besttvideo[ext=mp4]+besttaudio[ext=m4a]/mp4'" \
	yts="yt-dlp -f 'worstvideo[ext=mp4]+worstaudio[ext=m4a]/mp4'" \
	yta="yt-dlp -ci -f 'bestaudio[ext=m4a]'" \
  tdl="twitch-dl download" \
	webpull="rsync -avz lee@leegerken.org:/var/www/htdocs/leegerken.org/ ~/Website/ --delete" \
  py="python3" \
  q='exit' \

# git
alias \
  cfg="git --git-dir=$HOME/.config/.git/ --work-tree=$HOME" \

# editing shortcuts
alias \
	evim="vim $HOME/.config/vim/init.vim" \
	ebash="vim $HOME/.bashrc" \
  eprof="vim $HOME/.profile" \
	est="vim $HOME/.local/src/st/config.h" \
	edwm="vim $HOME/.local/src/dwm/config.h" \
	etmux="vim $HOME/.config/tmux/tmux.conf" \
  essh="vim $HOME/.ssh/config" \
  eweb="vim $HOME/Website/index.html" \
  estyle="vim $HOME/Website/style.css" \

# directory shortcuts
alias \
  cs="cd $HOME/iCloud/Courses/CS3060 ; ranger" \

# tmux
alias \
	ta="tmux attach -t" \
	tn="tmux new -s" \
	tl="tmux list-sessions" \
